<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>AWS SDK implementation of the fluent DynamoDB repository.</Description>
    <PackageId>Professional.DynamoDb.Repository.Aws</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DynamoDb.Repository/DynamoDb.Repository.csproj" />
    <PackageReference Include="AWSSDK.DynamoDBv2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
